homework
dstrekelj/algebra-front-end-developer-2019 pull request #71
Opened 2020-11-08 15:40 UTC by MPacak

kopirala sam sve exercise foldere, ali još nisam sve napravila. Sljedeće bi samo commitala nove fileove koje napravim. Prva dva zadatka su obavljena.

2020-11-15 20:01 UTC, dstrekelj requested changes
Odličan SVG 😄 Razumijem zašto si onda išla easy sa zastavama!

Ima sitnica koje bi volio vidjeti popravljene. I malo pazi na urednost, u nekim dokumentima imaš viška praznih linija 🙂

2020-11-15 20:01 UTC, dstrekelj commented on students/MPacak/module-2-html/exercises/07-class-register/1a.html
> +                <th scope="col">First Name</th>
Nedostaje `<tr>` koji je roditelj za `<th>` ćelije.

2020-11-15 20:01 UTC, dstrekelj commented on students/MPacak/module-2-html/exercises/07-class-register/1b.html
> +                <th scope="col">First Name</th>
Ista zamjerka kao u prethodnom dokumentu.

2020-11-19 18:11 UTC, MPacak commented on students/MPacak/module-2-html/exercises/06-top-5-songs/index.html
> +            #1 <br>
```može ovako?
         <li>
            <strong>Artist:</strong> Broke For Free <br>
            <strong>Track:</strong> Night Owl <br>
            Album: Directionless EP <br>
            Genre: Electronic, Minimal <br>
            </li> 
            <audio src="./Broke_For_Free_-_01_-_Night_Owl.mp3" controls></audio>
```

2020-12-05 18:56 UTC, dstrekelj commented on students/MPacak/module-2-html/exercises/06-top-5-songs/index.html
> +            #1 <br>
Unutar <ol> i <ul> smiju biti samo <li> elementi, tako da taj <audio> element moraš premjestiti. Kada to napraviš onda je to ok :)

2021-01-24 15:43 UTC, merged